// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-A1Hp6qs0jZpavyP_jUS4gxbRIaWY2FA',
    appId: '1:858651236290:web:3ec520f7ede4b6359b685b',
    messagingSenderId: '858651236290',
    projectId: 'letschat-1b67b',
    authDomain: 'letschat-1b67b.firebaseapp.com',
    storageBucket: 'letschat-1b67b.appspot.com',
    measurementId: 'G-0LE0FML6F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwUoJLhS3BFsEGUVHCKXe1ez2RgssqaM',
    appId: '1:858651236290:android:69aa57d51a84a02c9b685b',
    messagingSenderId: '858651236290',
    projectId: 'letschat-1b67b',
    storageBucket: 'letschat-1b67b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-vW5Q_Nk4UDp6wceAOky6a9Dna08ZsUc',
    appId: '1:858651236290:ios:b98d50adfbe944779b685b',
    messagingSenderId: '858651236290',
    projectId: 'letschat-1b67b',
    storageBucket: 'letschat-1b67b.appspot.com',
    iosBundleId: 'com.example.flutterLetsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-vW5Q_Nk4UDp6wceAOky6a9Dna08ZsUc',
    appId: '1:858651236290:ios:b98d50adfbe944779b685b',
    messagingSenderId: '858651236290',
    projectId: 'letschat-1b67b',
    storageBucket: 'letschat-1b67b.appspot.com',
    iosBundleId: 'com.example.flutterLetsChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-A1Hp6qs0jZpavyP_jUS4gxbRIaWY2FA',
    appId: '1:858651236290:web:702453e2bb7b91659b685b',
    messagingSenderId: '858651236290',
    projectId: 'letschat-1b67b',
    authDomain: 'letschat-1b67b.firebaseapp.com',
    storageBucket: 'letschat-1b67b.appspot.com',
    measurementId: 'G-F1XF2QQD8D',
  );

}